/**
 * @opengenerator/adapter-fastify
 *
 * Fastify adapter for OpenGenerator.
 * Transforms generated code for Fastify framework.
 */

import type {
  AdapterPlugin,
  AdapterOptions,
  GeneratedCode,
  GeneratedFile,
  Dependency,
  FrameworkType,
} from '@opengenerator/core'

export interface FastifyAdapterOptions {
  /**
   * Generate JSON schema validation
   */
  validation?: boolean

  /**
   * Generate Swagger/OpenAPI documentation
   */
  swagger?: boolean

  /**
   * Generate rate limiting
   */
  rateLimiting?: boolean

  /**
   * Generate CORS
   */
  cors?: boolean

  /**
   * Generate helmet security
   */
  helmet?: boolean

  /**
   * Generate logging
   */
  logging?: boolean

  /**
   * Router prefix
   */
  prefix?: string

  /**
   * Use TypeBox schemas
   */
  typebox?: boolean
}

const DEFAULT_OPTIONS: FastifyAdapterOptions = {
  validation: true,
  swagger: true,
  rateLimiting: false,
  cors: true,
  helmet: true,
  logging: true,
  prefix: '/api',
  typebox: true,
}

/**
 * Generate TypeBox base schemas
 */
function generateSchemas(): string {
  const lines: string[] = [
    '/**',
    ' * Fastify TypeBox Schemas',
    ' * Auto-generated by @opengenerator/adapter-fastify',
    ' */',
    '',
    "import { Type, Static } from '@sinclair/typebox'",
    '',
    '// Pagination schema',
    'export const PaginationSchema = Type.Object({',
    '  page: Type.Optional(Type.Integer({ minimum: 1, default: 1 })),',
    '  limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100, default: 20 })),',
    '  sortBy: Type.Optional(Type.String()),',
    "  sortOrder: Type.Optional(Type.Union([Type.Literal('asc'), Type.Literal('desc')])),",
    '})',
    '',
    'export type Pagination = Static<typeof PaginationSchema>',
    '',
    '// ID param schema',
    'export const IdParamSchema = Type.Object({',
    '  id: Type.String(),',
    '})',
    '',
    'export type IdParam = Static<typeof IdParamSchema>',
    '',
  ]

  return lines.join('\n')
}

/**
 * Generate Fastify plugin
 */
function generatePlugin(_options: FastifyAdapterOptions): string {
  const lines: string[] = [
    '/**',
    ' * Fastify Plugin',
    ' * Auto-generated by @opengenerator/adapter-fastify',
    ' */',
    '',
    "import { FastifyPluginAsync } from 'fastify'",
    "import fp from 'fastify-plugin'",
    '',
    'export interface PluginContext {',
    '  repositories: Record<string, unknown>',
    '}',
    '',
    'const apiPlugin: FastifyPluginAsync<PluginContext> = async (fastify, options) => {',
    '  const { repositories } = options',
    '',
    "  fastify.get('/health', async () => {",
    "    return { status: 'ok', timestamp: new Date().toISOString() }",
    '  })',
    '',
    '  // Add your routes here using the repositories from context',
    '}',
    '',
    "export default fp(apiPlugin, { name: 'api-plugin' })",
    '',
  ]

  return lines.join('\n')
}

/**
 * Generate app setup
 */
function generateApp(options: FastifyAdapterOptions): string {
  const lines: string[] = [
    '/**',
    ' * Fastify App Setup',
    ' * Auto-generated by @opengenerator/adapter-fastify',
    ' */',
    '',
    "import Fastify, { FastifyInstance } from 'fastify'",
  ]

  if (options.cors) {
    lines.push("import cors from '@fastify/cors'")
  }
  if (options.helmet) {
    lines.push("import helmet from '@fastify/helmet'")
  }
  if (options.swagger) {
    lines.push("import swagger from '@fastify/swagger'")
    lines.push("import swaggerUi from '@fastify/swagger-ui'")
  }

  lines.push("import apiPlugin, { PluginContext } from './plugin'")
  lines.push('')

  lines.push('export interface AppOptions extends PluginContext {')
  lines.push('  logger?: boolean')
  lines.push('}')
  lines.push('')

  lines.push('export async function createApp(options: AppOptions): Promise<FastifyInstance> {')
  lines.push('  const fastify = Fastify({')
  lines.push('    logger: options.logger ?? true,')
  lines.push('  })')
  lines.push('')

  if (options.helmet) {
    lines.push('  await fastify.register(helmet)')
  }
  if (options.cors) {
    lines.push('  await fastify.register(cors)')
  }
  if (options.swagger) {
    lines.push('  await fastify.register(swagger, {')
    lines.push('    openapi: {')
    lines.push("      info: { title: 'API', version: '1.0.0' },")
    lines.push('    },')
    lines.push('  })')
    lines.push('  await fastify.register(swaggerUi, {')
    lines.push("    routePrefix: '/docs',")
    lines.push('  })')
  }

  lines.push('')
  lines.push(`  await fastify.register(apiPlugin, {`)
  lines.push('    repositories: options.repositories,')
  lines.push(`  }, { prefix: '${options.prefix || '/api'}' })`)
  lines.push('')
  lines.push('  return fastify')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate index
 */
function generateIndex(): string {
  return `/**
 * Fastify Adapter - Main Entry
 * Auto-generated by @opengenerator/adapter-fastify
 */

export { createApp, type AppOptions } from './app'
export { default as apiPlugin, type PluginContext } from './plugin'
export * from './schemas'
`
}

/**
 * Create the Fastify adapter plugin
 */
export function createFastifyAdapter(options: FastifyAdapterOptions = {}): AdapterPlugin {
  const mergedOptions = { ...DEFAULT_OPTIONS, ...options }

  return {
    name: '@opengenerator/adapter-fastify',
    version: '1.0.0',
    framework: 'fastify' as FrameworkType,

    async adapt(code: GeneratedCode, _options: AdapterOptions): Promise<GeneratedCode> {
      const files: GeneratedFile[] = [...code.files]

      files.push({
        path: 'schemas.ts',
        content: generateSchemas(),
        type: 'source',
      })

      files.push({
        path: 'plugin.ts',
        content: generatePlugin(mergedOptions),
        type: 'source',
      })

      files.push({
        path: 'app.ts',
        content: generateApp(mergedOptions),
        type: 'source',
      })

      files.push({
        path: 'index.ts',
        content: generateIndex(),
        type: 'source',
      })

      // Merge dependencies
      const dependencies: Dependency[] = [
        ...(code.dependencies || []),
        ...this.getDependencies(),
      ]

      return {
        files,
        dependencies,
        metadata: {
          ...code.metadata,
          adapter: '@opengenerator/adapter-fastify',
          version: '1.0.0',
          generatedAt: new Date().toISOString(),
          options: mergedOptions,
        },
      }
    },

    getDependencies(): Dependency[] {
      const deps: Dependency[] = [
        { name: 'fastify', version: '^4.25.0', dev: false },
        { name: 'fastify-plugin', version: '^4.5.0', dev: false },
        { name: '@sinclair/typebox', version: '^0.32.0', dev: false },
      ]

      if (mergedOptions.cors) {
        deps.push({ name: '@fastify/cors', version: '^8.5.0', dev: false })
      }
      if (mergedOptions.helmet) {
        deps.push({ name: '@fastify/helmet', version: '^11.1.0', dev: false })
      }
      if (mergedOptions.swagger) {
        deps.push(
          { name: '@fastify/swagger', version: '^8.14.0', dev: false },
          { name: '@fastify/swagger-ui', version: '^2.1.0', dev: false }
        )
      }

      return deps
    },
  }
}

export const fastifyAdapter = createFastifyAdapter()
export default fastifyAdapter
