packages:
  - "packages/*"
  - "packages/parsers/*"
  - "packages/generators/*"
  - "packages/adapters/*"
  - "packages/auth/*"
  - "packages/database/*"
  - "packages/deploy/*"
  - "packages/presets/*"
  - "apps/*"
  - "examples/*"
