/**
 * @opengenerator/adapter-koa
 *
 * Koa adapter for OpenGenerator.
 * Transforms generated code for Koa framework.
 */

import type {
  AdapterPlugin,
  AdapterOptions,
  GeneratedCode,
  GeneratedFile,
  Dependency,
  FrameworkType,
} from '@opengenerator/core'

export interface KoaAdapterOptions {
  validation?: boolean
  cors?: boolean
  logging?: boolean
  prefix?: string
}

const DEFAULT_OPTIONS: KoaAdapterOptions = {
  validation: true,
  cors: true,
  logging: true,
  prefix: '/api',
}

/**
 * Generate Koa router
 */
function generateRouter(options: KoaAdapterOptions): string {
  const lines: string[] = [
    '/**',
    ' * Koa Router',
    ' * Auto-generated by @opengenerator/adapter-koa',
    ' */',
    '',
    "import Router from 'koa-router'",
    "import { Context } from 'koa'",
    '',
    'export interface RouterContext {',
    '  repositories: Record<string, unknown>',
    '}',
    '',
    'export function createRouter(context: RouterContext): Router {',
    `  const router = new Router({ prefix: '${options.prefix}' })`,
    '',
    "  router.get('/health', async (ctx: Context) => {",
    "    ctx.body = { status: 'ok', timestamp: new Date().toISOString() }",
    '  })',
    '',
    '  // Add your routes here using the context.repositories',
    '',
    '  return router',
    '}',
    '',
  ]

  return lines.join('\n')
}

/**
 * Generate Koa app
 */
function generateApp(options: KoaAdapterOptions): string {
  return `/**
 * Koa App Setup
 */

import Koa from 'koa'
import bodyParser from 'koa-bodyparser'
${options.cors ? "import cors from '@koa/cors'" : ''}
${options.logging ? "import logger from 'koa-logger'" : ''}
import { createRouter, RouterContext } from './router'

export interface AppOptions extends RouterContext {}

export function createApp(options: AppOptions): Koa {
  const app = new Koa()

  ${options.cors ? 'app.use(cors())' : ''}
  ${options.logging ? 'app.use(logger())' : ''}
  app.use(bodyParser())

  const router = createRouter(options)
  app.use(router.routes())
  app.use(router.allowedMethods())

  return app
}
`
}

/**
 * Generate index file
 */
function generateIndex(): string {
  return `export { createApp, type AppOptions } from './app'
export { createRouter, type RouterContext } from './router'
`
}

/**
 * Create the Koa adapter plugin
 */
export function createKoaAdapter(options: KoaAdapterOptions = {}): AdapterPlugin {
  const mergedOptions = { ...DEFAULT_OPTIONS, ...options }

  return {
    name: '@opengenerator/adapter-koa',
    version: '1.0.0',
    framework: 'koa' as FrameworkType,

    async adapt(code: GeneratedCode, _options: AdapterOptions): Promise<GeneratedCode> {
      const files: GeneratedFile[] = [...code.files]

      files.push({
        path: 'router.ts',
        content: generateRouter(mergedOptions),
        type: 'source',
      })
      files.push({
        path: 'app.ts',
        content: generateApp(mergedOptions),
        type: 'source',
      })
      files.push({
        path: 'index.ts',
        content: generateIndex(),
        type: 'source',
      })

      // Merge dependencies
      const dependencies: Dependency[] = [
        ...(code.dependencies || []),
        ...this.getDependencies(),
      ]

      return {
        files,
        dependencies,
        metadata: {
          ...code.metadata,
          adapter: '@opengenerator/adapter-koa',
          version: '1.0.0',
          options: mergedOptions,
        },
      }
    },

    getDependencies(): Dependency[] {
      const deps: Dependency[] = [
        { name: 'koa', version: '^2.15.0', dev: false },
        { name: 'koa-router', version: '^12.0.0', dev: false },
        { name: 'koa-bodyparser', version: '^4.4.0', dev: false },
        { name: '@types/koa', version: '^2.14.0', dev: true },
        { name: '@types/koa-router', version: '^7.4.8', dev: true },
        { name: '@types/koa-bodyparser', version: '^4.3.12', dev: true },
      ]

      if (mergedOptions.cors) {
        deps.push({ name: '@koa/cors', version: '^5.0.0', dev: false })
      }
      if (mergedOptions.logging) {
        deps.push({ name: 'koa-logger', version: '^3.2.1', dev: false })
      }

      return deps
    },
  }
}

export const koaAdapter = createKoaAdapter()
export default koaAdapter
