/**
 * Basic CRUD Example
 * Demonstrates simple REST API generation with OpenGenerator
 */

import Fastify from 'fastify'
import cors from '@fastify/cors'
import swagger from '@fastify/swagger'
import swaggerUi from '@fastify/swagger-ui'

// Import generated routes
// import { postRoutes } from './generated/post/post.routes'
// import { userRoutes } from './generated/user/user.routes'

const fastify = Fastify({
  logger: true,
})

async function main() {
  // Register plugins
  await fastify.register(cors)

  await fastify.register(swagger, {
    openapi: {
      info: {
        title: 'Basic CRUD API',
        version: '1.0.0',
        description: 'A simple CRUD API generated by OpenGenerator',
      },
    },
  })

  await fastify.register(swaggerUi, {
    routePrefix: '/docs',
  })

  // Health check
  fastify.get('/health', async () => ({
    status: 'ok',
    timestamp: new Date().toISOString(),
  }))

  // Register generated routes
  // await fastify.register(postRoutes, { prefix: '/api/posts' })
  // await fastify.register(userRoutes, { prefix: '/api/users' })

  // Example manual routes (before generation)
  fastify.get('/api/posts', async () => ({
    message: 'Run `pnpm generate` to generate the routes!',
    data: [],
  }))

  fastify.get('/api/users', async () => ({
    message: 'Run `pnpm generate` to generate the routes!',
    data: [],
  }))

  // Start server
  const port = Number(process.env.PORT) || 3000
  await fastify.listen({ port, host: '0.0.0.0' })

  console.log(`
  🚀 Server running at http://localhost:${port}
  📚 Swagger docs at http://localhost:${port}/docs

  To generate the API:
  1. pnpm db:push (create database)
  2. pnpm generate (generate routes)
  3. Uncomment imports in src/index.ts
  `)
}

main().catch(console.error)
