/**
 * Basic CRUD Example
 * Demonstrates a complete REST API generated with OpenGenerator
 *
 * Run with: pnpm dev
 */

import { createApp, type ServerContext } from './generated/server'

// In-memory storage for demo purposes
// In production, replace with actual database
const storage = {
  users: new Map<string, Record<string, unknown>>(),
  posts: new Map<string, Record<string, unknown>>(),
  comments: new Map<string, Record<string, unknown>>(),
}

// Helper to create repository for any entity
function createRepository(store: Map<string, Record<string, unknown>>) {
  return {
    findMany: async () => Array.from(store.values()),
    findById: async (id: string) => store.get(id),
    create: async (data: Record<string, unknown>) => {
      const id = crypto.randomUUID()
      const record = { ...data, id, createdAt: new Date().toISOString() }
      store.set(id, record)
      return record
    },
    update: async (id: string, data: Record<string, unknown>) => {
      const existing = store.get(id)
      if (!existing) return null
      const updated = { ...existing, ...data, updatedAt: new Date().toISOString() }
      store.set(id, updated)
      return updated
    },
    delete: async (id: string) => {
      const existed = store.has(id)
      store.delete(id)
      return existed
    },
  }
}

// Create context with repositories
const context: ServerContext = {
  repositories: {
    user: createRepository(storage.users),
    post: createRepository(storage.posts),
    comment: createRepository(storage.comments),
  },
}

// Create the app
const app = createApp(context)

// Start server
const PORT = parseInt(process.env.PORT || '3000', 10)

app.listen(PORT, '0.0.0.0').then(() => {
  console.log(`
  ╔════════════════════════════════════════════════════════════╗
  ║                   Basic CRUD API                           ║
  ║              Generated by OpenGenerator                    ║
  ╠════════════════════════════════════════════════════════════╣
  ║                                                            ║
  ║  Server running at: http://localhost:${PORT}                 ║
  ║  Health check:      http://localhost:${PORT}/health          ║
  ║                                                            ║
  ╠════════════════════════════════════════════════════════════╣
  ║  Available Endpoints (defined in routes.ts):               ║
  ║                                                            ║
  ║  Users:    GET|POST /api/v1/user                          ║
  ║            GET|PUT|DELETE /api/v1/user/:id                ║
  ║                                                            ║
  ║  Posts:    GET|POST /api/v1/post                          ║
  ║            GET|PUT|DELETE /api/v1/post/:id                ║
  ║                                                            ║
  ║  Comments: GET|POST /api/v1/comment                       ║
  ║            GET|PUT|DELETE /api/v1/comment/:id             ║
  ║                                                            ║
  ║  OpenAPI Spec: See ./generated/openapi.json               ║
  ║                                                            ║
  ╚════════════════════════════════════════════════════════════╝
  `)
})
