/**
 * @opengenerator/adapter-hono
 *
 * Hono adapter for OpenGenerator.
 * Transforms generated code for Hono framework optimized for edge runtimes.
 */

import type {
  AdapterPlugin,
  AdapterOptions,
  GeneratedCode,
  GeneratedFile,
  Dependency,
  FrameworkType,
} from '@opengenerator/core'

export interface HonoAdapterOptions {
  validation?: boolean
  cors?: boolean
  logging?: boolean
  openapi?: boolean
  prefix?: string
  runtime?: 'cloudflare' | 'vercel' | 'deno' | 'bun' | 'node'
}

const DEFAULT_OPTIONS: HonoAdapterOptions = {
  validation: true,
  cors: true,
  logging: true,
  openapi: true,
  prefix: '/api',
  runtime: 'node',
}

/**
 * Generate Hono app wrapper that integrates the generated code
 */
function generateHonoWrapper(options: HonoAdapterOptions): string {
  const lines: string[] = [
    '/**',
    ' * Hono App Wrapper',
    ' * Auto-generated by @opengenerator/adapter-hono',
    ' */',
    '',
    "import { Hono } from 'hono'",
    "import { cors } from 'hono/cors'",
    "import { logger } from 'hono/logger'",
    "import { prettyJSON } from 'hono/pretty-json'",
    "import { HTTPException } from 'hono/http-exception'",
  ]

  if (options.validation) {
    lines.push("import { zValidator } from '@hono/zod-validator'")
  }

  lines.push('')
  lines.push('export interface AppContext {')
  lines.push('  repositories: Record<string, unknown>')
  lines.push('  user?: { id: string; [key: string]: unknown }')
  lines.push('}')
  lines.push('')

  lines.push('export function createApp(context: AppContext) {')
  lines.push('  const app = new Hono()')
  lines.push('')

  if (options.cors) {
    lines.push('  app.use("*", cors())')
  }
  if (options.logging) {
    lines.push('  app.use("*", logger())')
  }
  lines.push('  app.use("*", prettyJSON())')
  lines.push('')

  lines.push("  app.get('/health', (c) => c.json({ status: 'ok' }))")
  lines.push('')

  lines.push('  app.onError((err, c) => {')
  lines.push('    if (err instanceof HTTPException) {')
  lines.push('      return c.json({ error: err.message }, err.status)')
  lines.push('    }')
  lines.push("    return c.json({ error: 'Internal Server Error' }, 500)")
  lines.push('  })')
  lines.push('')

  lines.push('  return app')
  lines.push('}')
  lines.push('')

  lines.push('export type AppType = ReturnType<typeof createApp>')
  lines.push('')

  return lines.join('\n')
}

function generateIndex(): string {
  return `/**
 * Hono Adapter - Main Entry
 */

export { createApp, type AppContext, type AppType } from './hono-wrapper'
`
}

/**
 * Create the Hono adapter plugin
 */
export function createHonoAdapter(options: HonoAdapterOptions = {}): AdapterPlugin {
  const mergedOptions = { ...DEFAULT_OPTIONS, ...options }

  return {
    name: '@opengenerator/adapter-hono',
    version: '1.0.0',
    framework: 'hono' as FrameworkType,

    async adapt(code: GeneratedCode, _options: AdapterOptions): Promise<GeneratedCode> {
      const files: GeneratedFile[] = [...code.files]

      // Add Hono-specific wrapper files
      files.push({
        path: 'hono-wrapper.ts',
        content: generateHonoWrapper(mergedOptions),
        type: 'source',
      })
      files.push({
        path: 'index.ts',
        content: generateIndex(),
        type: 'source',
      })

      // Merge dependencies
      const dependencies: Dependency[] = [
        ...(code.dependencies || []),
        ...this.getDependencies(),
      ]

      return {
        files,
        dependencies,
        metadata: {
          ...code.metadata,
          adapter: '@opengenerator/adapter-hono',
          version: '1.0.0',
          options: mergedOptions,
        },
      }
    },

    getDependencies(): Dependency[] {
      const deps: Dependency[] = [
        { name: 'hono', version: '^4.0.0', dev: false },
      ]

      if (mergedOptions.validation) {
        deps.push(
          { name: '@hono/zod-validator', version: '^0.2.0', dev: false },
          { name: 'zod', version: '^3.22.0', dev: false }
        )
      }

      return deps
    },
  }
}

export const honoAdapter = createHonoAdapter()
export default honoAdapter
